### ISSUE TITLE
Output of c2s.preprocess is inconsistent

### ISSUE THREAD

**Issue by mpmbq2** [lucastheis/c2s#11]
When using `c2s.preprocess` if the fps parameter is set such that the sampling rate does not need to be adjusted (i.e. the same sampling rate as the original image), the resulting `preprocessed_output[0]['calcium']` is an array of shape (frames,). However, if fps is set such that the sampling rate of the data _**does**_ need to be adjusted, the `preprocessed_output[0]['calcium']` is an array of shape (1, frames). This is problematic when matching the sampling rates of multiple images. I am attaching a screenshot from jupyter notebook as an example. `In 19:` is a packaging step; `In 35:` sets fps to require re-sampling, and `In 36:` is using the original sampling rate of the image.

I will continue to look for a fix, but I wanted to also bring it to your attention.

![screenshot from 2016-08-29 11 25 58](https://cloud.githubusercontent.com/assets/15681059/18056899/dfef32fe-6ddb-11e6-93c9-c1676492f7bd.png)

System Info: Ubuntu 14.04, Python 2.7.12

**Comment by mpmbq2** [comment]
I believe this issue can be fixed by removing the `.reshape(1, -1)` method from line 239 of c2s.py. Is there a problem with doing this that I am missing?

**Comment by lucastheis** [comment]
`preprocess` assumed that if spike trains or spike times are given as input, it is already in the correct format (1xN). It probably shouldn't, so I changed it:
