### ISSUE TITLE
random seed initialization fails because value is too big

### ISSUE THREAD

**Issue by jonasrauber** [lucastheis/c2s#4]
Running for example `c2s evaluate data.preprocessed.pck` throws an error:
```
Traceback (most recent call last):
  File "/usr/local/bin/c2s", line 43, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/c2s", line 38, in main
    return __import__('c2s-{0}'.format(args.command)).main([' '.join(argv[:2])] + argv[2:])
  File "/usr/local/bin/c2s-evaluate.py", line 33, in main
    experiment = Experiment()
  File "/usr/local/lib/python2.7/site-packages/c2s/experiment.py", line 154, in __init__
    random.seed(self.seed)
  File "mtrand.pyx", line 649, in mtrand.RandomState.seed (numpy/random/mtrand/mtrand.c:7699)
ValueError: Seed must be between 0 and 4294967295
```
Other commands like `c2s predict` fail as well.

The problem seems to be in [line 151 of experiment.py](https://github.com/lucastheis/c2s/blob/master/c2s/experiment.py#L151). The initialization of `self.seed` using `self.seed = int((time() + 1e6 * rand()) * 1e3)` creates values that are much bigger than 4294967295, which is the limit for `numpy.random.seed`.

Python's own random.seed does not seem have this limit, however, it already fails at [line 154 of experiment.py](https://github.com/lucastheis/c2s/blob/master/c2s/experiment.py#L154) `random.seed(self.seed)` because that line is doing exactly the same as the following line `numpy.random.seed(self.seed)` (see `from numpy import random`).

System Information: OS X, Python 2.7.9 (version from brew)

**Comment by jonasrauber** [comment]
This error seems to be caused by a [bugfix in numpy](https://github.com/numpy/numpy/commit/6b1a1205eac6fe5d162f16155d500765e8bca53c). Therefore, it only occurs when using newer numpy versions.

**Comment by lucastheis** [comment]
Thanks, Jonas! This should fix it (https://github.com/lucastheis/c2s/commit/0633333facc64bbb20bd322af96836ae72a22120).

**Comment by jonasrauber** [comment]
Yes, that fixed it, but you should probably also remove line 154 or 155 as they are identical (not really a bug).

**Comment by lucastheis** [comment]
I think NumPy has its own random seed, that's why I set both Python's and NumPy's seed. If you play around with

```python
numpy.random.seed(3)
random.seed(1)
print numpy.random.rand()
print random.random()
```

you will see that `random.seed` only affects `random.random`. If it was identical to `numpy.random.seed` it should affect both lines.

**Comment by jonasrauber** [comment]
In general you are right, but you imported numpy.random using `from numpy import random`, see [line 26](https://github.com/lucastheis/c2s/blob/master/c2s/experiment.py#L26). Therefore, you are effectively calling numpy.random.seed twice and that's also why the error is already thrown in line 154.

So I guess the solution would be to remove the import statement `from numpy import random` and leave both line 154 and 155.

**Comment by jonasrauber** [comment]
To clarify: I think the current code does not initialize Python's own random seed but only NumPy's random seed (twice!).

**Comment by lucastheis** [comment]
Got it, now it should do what I intended (https://github.com/lucastheis/c2s/commit/21093e8881dfca6316d8f3462330bc3551056ad3). Thanks!

**Comment by khadkaashish** [comment]
> I think NumPy has its own random seed, that's why I set both Python's and NumPy's seed. If you play around with
> 
> ```python
> numpy.random.seed(3)
> random.seed(1)
> print numpy.random.rand()
> print random.random()
> ```
> 
> you will see that `random.seed` only affects `random.random`. If it was identical to `numpy.random.seed` it should affect both lines.

Code: 
 cfg = Config(locals().copy())
random.seed(cfg.settings['seed'])
np.random.seed(cfg.settings['seed'])

This code was giving a value error too.
Then I used random.seed(0)

Playing around with numpy actually worked for me too.
