### ISSUE TITLE
saving predict data into .mat 

### ISSUE THREAD

**Issue by ZeitgeberH** [lucastheis/c2s#9]
I am using Ubuntu 16.04 with Matlab 2016a. 

c2s was successfully build and could preprocessed data in Matlab format. But when i try to the predict function, it  did the calculation, but had problem to save it into .mat format. 

Something to do with Scipy/IO.

 File "/home/mhu/anaconda2/lib/python2.7/site-packages/scipy/io/matlab/mio5.py", line 443, in to_writeable
    return np.array([tuple(values)], dtype)
TypeError: data type not understood

**Comment by lucastheis** [comment]
It appears `scipy.io.savemat` does not support unicode keys, which we introduced with Python3 compatibility. It should now be fixed.

Thanks @ZeitgeberH.
